---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-canary
spec:
  selector:
    matchLabels:
      app: market-data
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: market-data
        tier: backend
        track: canary
    spec:
      containers:
      - name: market-data
        image: hashicorp/http-echo
        args: ["-text='hello world v2'"]
        resources: 
          limits:
            cpu: 120m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5678
        livenessProbe:
          httpGet:
            path: /ping
            port: 5678
          initialDelaySeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /ping
            port: 5678
          initialDelaySeconds: 10
          timeoutSeconds: 15
