---
kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: market-data
spec:
  selector:
    matchLabels:
      app: market-data
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: market-data
        tier: backend
        track: stable
    spec:
      containers:
      - name: market-data
        image: hashicorp/http-echo
        args: ["-text='hello world'"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5678
        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 10
          timeoutSeconds: 15
